spring:
  datasource:
    url: jdbc:mysql://mydb.cxdsbj1clk05.us-east-1.rds.amazonaws.com:3306/mydb
    username: admin
    password: master12
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
