spring:
  datasource:
    url: jdbc:mysql://database-1.cxdsbj1clk05.us-east-1.rds.amazonaws.com:3308/mydb
    username: admin
    password: master12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

    spring:
      jpa:
        properties:
          hibernate:
            globally_quoted_identifiers=true:
